# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c544811aa62df3059344d31cff54f0e597d945a0be2bcaa11c9eb4b70930af6b53cd053c74c23b923e78fe7e8f2453bd60ecdf453601ccf4f847e1b870a92ac

test:
  secret_key_base: 535600174698f257ca36a6a2ee6d28bc34b5581a7ffc6a4fea25cbd92bf4d03cda2115cb106eeb1f956f8ceca47ebaf4c6121fbc545d6c98ff6f62e53c315a7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
